### ISSUE TITLE
Add HCT logos to website

### ISSUE THREAD

**Issue by jpylvanainen** [Turku-Bioimaging/turku-bioimaging.github.io#25]

**Comment by jpylvanainen** [comment]
[Logos here](https://www.dropbox.com/sh/348xxrhybzqpmpx/AAACC1V7RkEFdgK-Ox_2VyqPa?dl=0)

**Comment by junelsolis** [comment]
HCT logo added in 9dc5364935818f2130579abf2476a21d6ff6a217
